# Generated by Django 4.1 on 2022-11-27 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=25)),
                ('haftalik_miqori', models.PositiveIntegerField(default=0)),
                ('oquv_davomiyligi', models.FloatField(default=0, help_text='Yillar hisobida')),
            ],
            options={
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=25)),
                ('oqish_yili', models.CharField(max_length=15, verbose_name="O'qish yili")),
                ('fan', models.ManyToManyField(blank=True, to='main.fan')),
            ],
            options={
                'verbose_name_plural': 'Guruhlar',
            },
        ),
        migrations.CreateModel(
            name='Oqituvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familya', models.CharField(max_length=25)),
                ('ism', models.CharField(max_length=25)),
                ('otasining_ismi', models.CharField(max_length=25)),
                ('telefon', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
        migrations.CreateModel(
            name='Qongiroq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('davomiyligi', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name': "Qo'ng'iroq Jadvali",
                'verbose_name_plural': "Qo'ngiroq Jadvallari",
            },
        ),
        migrations.CreateModel(
            name='Oquvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familya', models.CharField(max_length=25)),
                ('ism', models.CharField(max_length=25)),
                ('otasining_ismi', models.CharField(max_length=25)),
                ('telefon', models.CharField(max_length=25)),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.guruh')),
            ],
            options={
                'verbose_name': "O'quvchi",
                'verbose_name_plural': "O'quvchilar",
            },
        ),
        migrations.CreateModel(
            name='OqishNarxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tolov', models.FloatField(default=0.0, help_text="to'lov 1 ta dars uchun $ da hisoblanadi")),
                ('oylik_harajat', models.FloatField(default=0.0)),
                ('oqish_yili', models.CharField(max_length=25, verbose_name="o'qish yili")),
                ('fan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.fan')),
            ],
            options={
                'verbose_name_plural': "O'qish narxlari",
            },
        ),
        migrations.CreateModel(
            name='DasrJadvali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.guruh')),
                ('oqituvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.oqituvchi')),
            ],
            options={
                'verbose_name_plural': 'Dars Jadvallari',
            },
        ),
    ]
