# Generated by Django 4.1 on 2022-11-27 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dasrjadvali',
            name='tanaffus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.qongiroq'),
            preserve_default=False,
        ),
    ]
